dbt_transform:
  outputs:
    dev:
      dataset: namadataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: path/to/bigquerykey.json
      location: EU
      method: service-account
      priority: interactive
      project: namaproject
      threads: 1
      type: bigquery
  target: dev
